/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Shopkeeper = IDL.Record({
  'id' : IDL.Nat,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'shopName' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const DashboardMetrics = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalStockValue' : IDL.Nat,
  'connectedShopkeepers' : IDL.Nat,
  'shortlistedProducts' : IDL.Nat,
  'lowStockItems' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Nat,
  'name' : IDL.Text,
  'wholesalePrice' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'amenities' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'isShortlisted' : IDL.Bool,
  'price' : IDL.Nat,
  'warranty' : IDL.Text,
  'isTrending' : IDL.Bool,
  'shopkeeperId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllShopkeepers' : IDL.Func([], [IDL.Vec(Shopkeeper)], ['query']),
  'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
  'getLowStockProducts' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getShopkeeperById' : IDL.Func([IDL.Nat], [Shopkeeper], ['query']),
  'getShortlistedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'registerShopkeeper' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'setTrending' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'toggleShortlist' : IDL.Func([IDL.Nat], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateStockQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Shopkeeper = IDL.Record({
    'id' : IDL.Nat,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'shopName' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const DashboardMetrics = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalStockValue' : IDL.Nat,
    'connectedShopkeepers' : IDL.Nat,
    'shortlistedProducts' : IDL.Nat,
    'lowStockItems' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Nat,
    'name' : IDL.Text,
    'wholesalePrice' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'amenities' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'isShortlisted' : IDL.Bool,
    'price' : IDL.Nat,
    'warranty' : IDL.Text,
    'isTrending' : IDL.Bool,
    'shopkeeperId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllShopkeepers' : IDL.Func([], [IDL.Vec(Shopkeeper)], ['query']),
    'getDashboardMetrics' : IDL.Func([], [DashboardMetrics], ['query']),
    'getLowStockProducts' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getShopkeeperById' : IDL.Func([IDL.Nat], [Shopkeeper], ['query']),
    'getShortlistedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getTrendingProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'registerShopkeeper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'setTrending' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'toggleShortlist' : IDL.Func([IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateStockQuantity' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };