/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardMetrics {
  'totalProducts' : bigint,
  'totalStockValue' : bigint,
  'connectedShopkeepers' : bigint,
  'shortlistedProducts' : bigint,
  'lowStockItems' : bigint,
}
export interface Product {
  'id' : bigint,
  'mrp' : bigint,
  'name' : string,
  'wholesalePrice' : bigint,
  'tags' : Array<string>,
  'unit' : string,
  'description' : string,
  'discountPercent' : bigint,
  'amenities' : Array<string>,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'isShortlisted' : boolean,
  'price' : bigint,
  'warranty' : string,
  'isTrending' : boolean,
  'shopkeeperId' : bigint,
}
export interface Shopkeeper {
  'id' : bigint,
  'principal' : Principal,
  'name' : string,
  'shopName' : string,
  'category' : string,
  'phone' : string,
  'location' : string,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      Array<string>,
      Array<string>,
      string,
      bigint,
      string,
    ],
    bigint
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllShopkeepers' : ActorMethod<[], Array<Shopkeeper>>,
  'getDashboardMetrics' : ActorMethod<[], DashboardMetrics>,
  'getLowStockProducts' : ActorMethod<[[] | [bigint]], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getShopkeeperById' : ActorMethod<[bigint], Shopkeeper>,
  'getShortlistedProducts' : ActorMethod<[], Array<Product>>,
  'getTrendingProducts' : ActorMethod<[], Array<Product>>,
  'registerShopkeeper' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'setTrending' : ActorMethod<[bigint, boolean], undefined>,
  'toggleShortlist' : ActorMethod<[bigint], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      Array<string>,
      Array<string>,
      string,
      bigint,
      string,
    ],
    undefined
  >,
  'updateStockQuantity' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];